CREATE TABLE PERSONAS(
    PERSONA_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(40) NOT NULL,
    TELEFONO VARCHAR2(10) NOT NULL,
    PRIMARY KEY(PERSONA_ID),
    CONSTRAINT PERSONA_TELEFONO_CARACTERES CHECK (LENGTH(TELEFONO) = 10)
);

CREATE TABLE USUARIOS(
    PERSONA_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    PASS VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(40) NOT NULL,
    CARGO VARCHAR2(20) NOT NULL,
    PRIMARY KEY(PERSONA_ID),
    CONSTRAINT FK_USUARIOS_PERSONAS FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(PERSONA_ID),
    CONSTRAINT USUARIOS_USERNAME_UNICO UNIQUE(USERNAME),
    CONSTRAINT USUARIOS_CARGO_VALORES CHECK (CARGO IN ('ADMINISTRADOR', 'LOGISTICA', 'MANTENIMIENTO'))
);

CREATE TABLE LICENCIAS(
    LICENCIA_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    NUMERO_LICENCIA VARCHAR2(50) NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    PRIMARY KEY(LICENCIA_ID)
);

CREATE TABLE CHOFERES(
    PERSONA_ID NUMBER NOT NULL,
    COMISION NUMBER NULL,
    LICENCIA_ID NUMBER NULL,
    ESTADO VARCHAR2(30) DEFAULT 'DISPONIBLE' NOT NULL,
    PRIMARY KEY(PERSONA_ID),
    CONSTRAINT FK_CHOFERES_PERSONAS FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(PERSONA_ID),
    CONSTRAINT FK_CHOFERES_LICENCIAS FOREIGN KEY(LICENCIA_ID) REFERENCES LICENCIAS(LICENCIA_ID),
    CONSTRAINT CHOFERES_ESTADO_VALORES CHECK (ESTADO IN ('DISPONIBLE', 'EN_VIAJE', 'BAJA_TEMPORAL'))
);

CREATE TABLE CAMIONES(
    CAMION_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    PLACA VARCHAR2(20) NOT NULL,
    MODELO VARCHAR2(50) NOT NULL,
    CAPACIDAD NUMBER(10, 2) NOT NULL,
    ESTADO VARCHAR2(30) DEFAULT 'DISPONIBLE' NOT NULL,
    PRIMARY KEY(CAMION_ID),
    CONSTRAINT CAMIONES_ESTADO_VALORES CHECK (ESTADO IN ('DISPONIBLE', 'EN_VIAJE', 'MANTENIMIENTO'))
);

CREATE TABLE VIAJES(
    VIAJE_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    CAMION_ID NUMBER NOT NULL,
    CHOFER_ID NUMBER NOT NULL,
    ORIGEN VARCHAR2(80) NOT NULL,
    DESTINO VARCHAR2(80) NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    FECHA_ESTIMADA DATE NOT NULL,
    FECHA_ENTREGA DATE NULL,
    ESTADO VARCHAR2(50) DEFAULT 'EN_PREPARACION' NOT NULL,
    COSTO NUMBER(10, 2) NOT NULL,
    PRIMARY KEY(VIAJE_ID),
    CONSTRAINT FK_VIAJES_CAMIONES FOREIGN KEY(CAMION_ID) REFERENCES CAMIONES(CAMION_ID),
    CONSTRAINT FK_VIAJES_CHOFERES FOREIGN KEY(CHOFER_ID) REFERENCES CHOFERES(PERSONA_ID),
    CONSTRAINT VIAJES_ESTADO_VALORES CHECK (ESTADO IN ('EN_PREPARACION', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO'))
);



INSERT INTO PERSONAS (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO) 
VALUES ('Usuario', 'Administrador', 'Sistema', '0000000000');


INSERT INTO USUARIOS (PERSONA_ID, USERNAME, PASS, EMAIL, CARGO) 
VALUES (1, 'admin', 'admin', 'admin@sistema.com', 'ADMINISTRADOR');


